### ISSUE TITLE
Save scrapy output to S3 bucket

### ISSUE THREAD

**Issue by bstarling** [Data4Democracy/scrape-right#10]
Anyone with knowledge on how to do this in Python 3? Tried settings recommended [here](https://doc.scrapy.org/en/latest/topics/feed-exports.html) but did not get any errors or output in my test s3 bucket. I have tested placing files with boto directly and it works fine. Also tested changing `FEED_URI='file:///path/to/folder/export.json'` and it works fine

`AWS_ACCESS_KEY_ID='Key'`
`AWS_SECRET_ACCESS_KEY='Secret'`

`FEED_URI='s3://my-test-bucket/export.json'`
`FEED_FORMAT='json'`

Boto
```
In [2]: boto.__version__
Out[2]: '2.42.0'
```

**Comment by cavaunpeu** [comment]
I don't quite understand the problem.

> I have tested placing files with boto directly and it works fine.

Does this imply that you were successful when working out of a REPL, but unsuccessful when placing the same code into a `Pipeline` object (and adding it to the pipeline in `settings.py`)?

**Comment by bstarling** [comment]
It is possible I am not understanding how this functionality is supposed to be used. I was not adding code to pipeline but expecting it to work like the file backend.

For example when using the "file backend" simply adding below settings created a local json file which contains all the extracted items. No additions to pipeline needed. 

`FEED_URI='file:///path/to/folder/export.json`
`FEED_FORMAT='json'`

I was attempting to reproduce the same output I get in a local file but have the file placed to directly to a S3 bucket instead. Maybe I am just missing how it should work. I've seen lots of examples where each individual item is saved to a database in the pipeline code or examples to download and save images to s3 but nothing dealing with the export feed directly. This leads me to believe maybe this is not the right way to save your scrapy data to s3.

I have no problem creating the a local file via scrapy then sending it to s3 via boto (outside scrapy) but it seemed like scrapy has the functionality to skip the middle man here. The original thought was to save output from scrapy in s3 which would be picked up and saved into dynamo via a separate process. Perhaps it's best to save directly to dynamo in the pipeline?

**Comment by bstarling** [comment]
Looks like it was an issue with how scrapy was picking up credentials. After running AWS CLI config to create `~/aws/credentials` file it is *magically* working
